/**
 * @note   : DO NOT MODIFY!!! AUTOMATICALLY GENERATED BY dbc2c.py(V1.1.1)
 * @file   : Com_Signal_Cfg_BLE.h
 * @brief  : Define com signals config
 * @author : yangtl
 * @date   : 2025-06-06 16:31:20
 */
#ifndef __COM_SIGNAL_CFG_BLE_H__
#define __COM_SIGNAL_CFG_BLE_H__

#include <stdint.h>
#include "Com.h"

#ifdef __cplusplus
extern "C" {
#endif

#define COM_CHANNEL_BodyCAN             0  /*! Com channel: BodyCAN */
#define COM_TOUT_MUL                    10 /*! Multiple of the timeout period for receiving message */

/* Tx messages index of BLE */
typedef enum {
    MSG_TX_IDX_BLE_Status_0x100,              /*!< index=0, size=64bytes */
    MSG_TX_IDX_BLE_Control_0x101,             /*!< index=1, size=12bytes */

    BLE_MSG_TX_IDX_MAX,
} BLE_MsgsTxIndexType;

/* Rx messages index of BLE */
typedef enum {
    MSG_RX_IDX_VCU_VehicleStatus_0x200,       /*!< index=0, size=8bytes */

    BLE_MSG_RX_IDX_MAX,
} BLE_MsgsRxIndexType;

/* Tx signals index of BLE */
typedef enum {
    /* 0x100, BLE_Status, SignalsNumber=4 */
    SIG_TX_IDX_BLE_ConnectStatus_0x100,             /*!< index=0, len=1bit, The current connection status of the BLE module      # 1 "Connected" 0 "Disconnected" */
    SIG_TX_IDX_BLE_RSSI_0x100,                      /*!< index=1, len=8bit,  */
    SIG_TX_IDX_BLE_AdvertisingInterval_0x100,       /*!< index=2, len=8bit,  */
    SIG_TX_IDX_BLE_ScanInterval_0x100,              /*!< index=3, len=8bit,  */
    /* 0x101, BLE_Control, SignalsNumber=2 */
    SIG_TX_IDX_BLE_CarDoorControl_0x101,            /*!< index=4, len=1bit,       # 1 "Close" 0 "Open" */
    SIG_TX_IDX_BLE_CarWindowControl_0x101,          /*!< index=5, len=1bit,       # 1 "Close" 0 "Open" */

    BLE_SIG_TX_IDX_MAX,
} BLE_SignalsTxIndexType;

/* Rx signals index of BLE */
typedef enum {
    /* 0x200, VCU_VehicleStatus, SignalsNumber=4 */
    SIG_RX_IDX_VCU_VehicleGearStatus_0x200,         /*!< index=0, len=4bit,  */
    SIG_RX_IDX_VCU_VehicleGearValid_0x200,          /*!< index=1, len=1bit,       # 1 "invalid" 0 "valid" */
    SIG_RX_IDX_VCU_VehicleSpeedValid_0x200,         /*!< index=2, len=1bit,       # 1 "invalid" 0 "valid" */
    SIG_RX_IDX_VCU_VehicleSpeed_0x200,              /*!< index=3, len=16bit,  */

    BLE_SIG_RX_IDX_MAX,
} BLE_SignalsRxIndexType;

extern const ComTxSignalConfigType gTxSignalsCfg_BLE[BLE_SIG_TX_IDX_MAX];
extern const ComRxSignalConfigType gRxSignalsCfg_BLE[BLE_SIG_RX_IDX_MAX];

extern const ComTxPduConfigType gTxMsgsCfg_BLE[BLE_MSG_TX_IDX_MAX];
extern const ComRxPduConfigType gRxMsgsCfg_BLE[BLE_MSG_RX_IDX_MAX];

#ifdef __cplusplus
}
#endif

#endif /* __COM_SIGNAL_CFG_BLE_H__ */
