/**
 * @note   : DO NOT MODIFY!!! AUTOMATICALLY GENERATED BY dbc2c.py(V1.1.1)
 * @file   : Com_Signal_Cfg_BLE.c
 * @brief  : Define com signals config
 * @author : yangtl
 * @date   : 2025-06-06 16:31:20
 */
#include "Com.h"
#include "Com_Signal_Cfg_BLE.h"
#include "Com_Signal_Type_BLE.h"

static BLE_TxMsgsType sendMsgs;
static BLE_RxMsgsType recvMsgs;

/* Tx 0x100, BLE_Status, SignalsNumber=4 */

/* Signal length=1bit, value: 1 "Connected" 0 "Disconnected" */
void SetSignal_BLE_ConnectStatus_0x100(const void *pData)
{
    sendMsgs.BLE_Status_0x100.signal.BLE_ConnectStatus = *(uint8_t *)pData;
}

/* Signal length=8bit */
void SetSignal_BLE_RSSI_0x100(const void *pData)
{
    sendMsgs.BLE_Status_0x100.signal.BLE_RSSI = *(uint8_t *)pData;
}

/* Signal length=8bit */
void SetSignal_BLE_AdvertisingInterval_0x100(const void *pData)
{
    sendMsgs.BLE_Status_0x100.signal.BLE_AdvertisingInterval = *(uint8_t *)pData;
}

/* Signal length=8bit */
void SetSignal_BLE_ScanInterval_0x100(const void *pData)
{
    sendMsgs.BLE_Status_0x100.signal.BLE_ScanInterval = *(uint8_t *)pData;
}

/* Tx 0x101, BLE_Control, SignalsNumber=2 */

/* Signal length=1bit, value: 1 "Close" 0 "Open" */
void SetSignal_BLE_CarDoorControl_0x101(const void *pData)
{
    sendMsgs.BLE_Control_0x101.signal.BLE_CarDoorControl = *(uint8_t *)pData;
}

/* Signal length=1bit, value: 1 "Close" 0 "Open" */
void SetSignal_BLE_CarWindowControl_0x101(const void *pData)
{
    sendMsgs.BLE_Control_0x101.signal.BLE_CarWindowControl = *(uint8_t *)pData;
}

/* Rx 0x200, VCU_VehicleStatus, SignalsNumber=4 */

/* Signal length=4bit */
void GetSignal_VCU_VehicleGearStatus_0x200(void *pData)
{
    *(uint8_t *)pData = recvMsgs.VCU_VehicleStatus_0x200.signal.VCU_VehicleGearStatus;
}

/* Signal length=1bit, value: 1 "invalid" 0 "valid" */
void GetSignal_VCU_VehicleGearValid_0x200(void *pData)
{
    *(uint8_t *)pData = recvMsgs.VCU_VehicleStatus_0x200.signal.VCU_VehicleGearValid;
}

/* Signal length=1bit, value: 1 "invalid" 0 "valid" */
void GetSignal_VCU_VehicleSpeedValid_0x200(void *pData)
{
    *(uint8_t *)pData = recvMsgs.VCU_VehicleStatus_0x200.signal.VCU_VehicleSpeedValid;
}

/* Signal length=16bit */
void GetSignal_VCU_VehicleSpeed_0x200(void *pData)
{
    *(uint16_t *)pData = recvMsgs.VCU_VehicleStatus_0x200.signal.VCU_VehicleSpeed;
}

const ComTxSignalConfigType gTxSignalsCfg_BLE[BLE_SIG_TX_IDX_MAX] = {
    /*     PDU ID                              void (*pfnSetSignal)(const void *SignalDataPtr)                              */
    { MSG_TX_IDX_BLE_Status_0x100,             SetSignal_BLE_ConnectStatus_0x100           },
    { MSG_TX_IDX_BLE_Status_0x100,             SetSignal_BLE_RSSI_0x100                    },
    { MSG_TX_IDX_BLE_Status_0x100,             SetSignal_BLE_AdvertisingInterval_0x100     },
    { MSG_TX_IDX_BLE_Status_0x100,             SetSignal_BLE_ScanInterval_0x100            },
    { MSG_TX_IDX_BLE_Control_0x101,            SetSignal_BLE_CarDoorControl_0x101          },
    { MSG_TX_IDX_BLE_Control_0x101,            SetSignal_BLE_CarWindowControl_0x101        },
};

const ComRxSignalConfigType gRxSignalsCfg_BLE[BLE_SIG_RX_IDX_MAX] = {
    { MSG_RX_IDX_VCU_VehicleStatus_0x200,      GetSignal_VCU_VehicleGearStatus_0x200       },
    { MSG_RX_IDX_VCU_VehicleStatus_0x200,      GetSignal_VCU_VehicleGearValid_0x200        },
    { MSG_RX_IDX_VCU_VehicleStatus_0x200,      GetSignal_VCU_VehicleSpeedValid_0x200       },
    { MSG_RX_IDX_VCU_VehicleStatus_0x200,      GetSignal_VCU_VehicleSpeed_0x200            },
};

const ComTxPduConfigType gTxMsgsCfg_BLE[BLE_MSG_TX_IDX_MAX] = {
    {// 周期型
        { {0}, COM_MSG_PERIODIC,  .startOffsetP = 0, .cycleTime = 2000, .fastCycleTime = 0, .repetition = 0, .repeatTime = 0, .minDelayTime = 0 },// 发送策略配置
        { (uint8_t *)&(const ComPduMetaDataType){COM_CHANNEL_BodyCAN, 0x100}, sendMsgs.BLE_Status_0x100.frame, sizeof(sendMsgs.BLE_Status_0x100) },// 发送内容指定
    },
    {// 事件型
        { {0}, COM_MSG_ON_EVENT,  .startOffsetP = 0, .cycleTime = 0, .fastCycleTime = 20, .repetition = 3, .repeatTime = 20, .minDelayTime = 10 },
        { (uint8_t *)&(const ComPduMetaDataType){COM_CHANNEL_BodyCAN, 0x101}, sendMsgs.BLE_Control_0x101.frame, sizeof(sendMsgs.BLE_Control_0x101) },
    },
};

const ComRxPduConfigType gRxMsgsCfg_BLE[BLE_MSG_RX_IDX_MAX] = {
    {
        { {0},    500 * COM_TOUT_MUL },
        { (uint8_t *)&(const ComPduMetaDataType){COM_CHANNEL_BodyCAN, 0x200}, recvMsgs.VCU_VehicleStatus_0x200.frame, sizeof(recvMsgs.VCU_VehicleStatus_0x200) },
    },
};

